[build]
  publish = "."

[[redirects]]
  from = "/thankyou.html"
  to = "/thankyou.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact-success.html"
  status = 200

[[redirects]]
  from = "/volunteer"
  to = "/volunteer-success.html"
  status = 200

[[redirects]]
  from = "/donate"
  to = "/donate-success.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources-success.html"
  status = 200
